import type { TableData } from "../types/types"

export const tableData: TableData = {
  regions: ["CENTRAL TEXAS", "HOUSTON", "DALLAS", "AUSTIN METRO"],
  sites: [
    { name: "KYLE", region: "CENTRAL TEXAS" },
    { name: "GTWH", region: "CENTRAL TEXAS" },
    { name: "SMWW", region: "CENTRAL TEXAS" },
    { name: "COMM", region: "CENTRAL TEXAS" },
    { name: "SM35", region: "CENTRAL TEXAS" },
    { name: "AUST", region: "CENTRAL TEXAS" },
    { name: "ROCK", region: "CENTRAL TEXAS" },
    { name: "TMBL", region: "HOUSTON" },
    { name: "PSDA", region: "HOUSTON" },
    { name: "HWY6", region: "HOUSTON" },
    { name: "STFD", region: "HOUSTON" },
    { name: "SGLD", region: "HOUSTON" },
    { name: "BISS", region: "HOUSTON" },
  ],
  metrics: [
    // ==================== SALES (PACING) ====================
    {
      name: "SALES (PACING)",
      category: "SALES (PACING)",
      data: null,
    },
    {
      name: "Sales ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "246246", type: "currency" },
        GTWH: { value: "154187", type: "currency" },
        SMWW: { value: "-153261", type: "currency" },
        COMM: { value: "110728", type: "currency" },
        SM35: { value: "75532", type: "currency" },
        AUST: { value: "54657", type: "currency" },
        ROCK: { value: "26661", type: "currency" },
        TMBL: { value: "102239", type: "currency" },
        PSDA: { value: "69088", type: "currency" },
        HWY6: { value: "80313", type: "currency" },
        STFD: { value: "75940", type: "currency" },
        SGLD: { value: "93246", type: "currency" },
        BISS: { value: "58668", type: "currency" },
        TOTAL: { value: "1160780", type: "currency" },
        AVERAGE: { value: "116078", type: "currency" },
      },
    },
    {
      name: "Fuel Sales ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "191188", type: "currency" },
        GTWH: { value: "123059", type: "currency" },
        SMWW: { value: "-119607", type: "currency" },
        COMM: { value: "90846", type: "currency" },
        SM35: { value: "50423", type: "currency" },
        AUST: { value: "27260", type: "currency" },
        ROCK: { value: "15372", type: "currency" },
        TMBL: { value: "78016", type: "currency" },
        PSDA: { value: "51275", type: "currency" },
        HWY6: { value: "62225", type: "currency" },
        STFD: { value: "56344", type: "currency" },
        SGLD: { value: "66901", type: "currency" },
        BISS: { value: "46126", type: "currency" },
        TOTAL: { value: "889884", type: "currency" },
        AVERAGE: { value: "88988", type: "currency" },
      },
    },
    {
      name: "Recurring + Prepaid ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "191188", type: "currency" },
        GTWH: { value: "123059", type: "currency" },
        SMWW: { value: "-119607", type: "currency" },
        COMM: { value: "90846", type: "currency" },
        SM35: { value: "50423", type: "currency" },
        AUST: { value: "27260", type: "currency" },
        ROCK: { value: "15372", type: "currency" },
        TMBL: { value: "78016", type: "currency" },
        PSDA: { value: "51275", type: "currency" },
        HWY6: { value: "62225", type: "currency" },
        STFD: { value: "56344", type: "currency" },
        SGLD: { value: "66901", type: "currency" },
        BISS: { value: "46126", type: "currency" },
        TOTAL: { value: "889884", type: "currency" },
        AVERAGE: { value: "88988", type: "currency" },
      },
    },
    {
      name: "Recurring ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "179517", type: "currency" },
        GTWH: { value: "116992", type: "currency" },
        SMWW: { value: "115224", type: "currency" },
        COMM: { value: "85536", type: "currency" },
        SM35: { value: "46348", type: "currency" },
        AUST: { value: "14531", type: "currency" },
        ROCK: { value: "13406", type: "currency" },
        TMBL: { value: "76243", type: "currency" },
        PSDA: { value: "47672", type: "currency" },
        HWY6: { value: "59836", type: "currency" },
        STFD: { value: "54294", type: "currency" },
        SGLD: { value: "66851", type: "currency" },
        BISS: { value: "40551", type: "currency" },
        TOTAL: { value: "848653", type: "currency" },
        AVERAGE: { value: "84866", type: "currency" },
      },
    },
    {
      name: "Prepaid ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "11671", type: "currency" },
        GTWH: { value: "6066", type: "currency" },
        SMWW: { value: "4383", type: "currency" },
        COMM: { value: "5266", type: "currency" },
        SM35: { value: "3976", type: "currency" },
        AUST: { value: "12729", type: "currency" },
        ROCK: { value: "1966", type: "currency" },
        TMBL: { value: "1772", type: "currency" },
        PSDA: { value: "3603", type: "currency" },
        HWY6: { value: "2389", type: "currency" },
        STFD: { value: "2050", type: "currency" },
        SGLD: { value: "50", type: "currency" },
        BISS: { value: "5575", type: "currency" },
        TOTAL: { value: "41226", type: "currency" },
        AVERAGE: { value: "4123", type: "currency" },
      },
    },
    {
      name: "Retail ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "55057", type: "currency" },
        GTWH: { value: "31128", type: "currency" },
        SMWW: { value: "33654", type: "currency" },
        COMM: { value: "19882", type: "currency" },
        SM35: { value: "25108", type: "currency" },
        AUST: { value: "27397", type: "currency" },
        ROCK: { value: "11289", type: "currency" },
        TMBL: { value: "24223", type: "currency" },
        PSDA: { value: "17813", type: "currency" },
        HWY6: { value: "18089", type: "currency" },
        STFD: { value: "19596", type: "currency" },
        SGLD: { value: "26345", type: "currency" },
        BISS: { value: "12543", type: "currency" },
        TOTAL: { value: "270896", type: "currency" },
        AVERAGE: { value: "27090", type: "currency" },
      },
    },
    {
      name: "Recurring (%)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "73", type: "percentage" },
        GTWH: { value: "76", type: "percentage" },
        SMWW: { value: "75", type: "percentage" },
        COMM: { value: "77", type: "percentage" },
        SM35: { value: "61", type: "percentage" },
        AUST: { value: "27", type: "percentage" },
        ROCK: { value: "50", type: "percentage" },
        TMBL: { value: "75", type: "percentage" },
        PSDA: { value: "69", type: "percentage" },
        HWY6: { value: "75", type: "percentage" },
        STFD: { value: "71", type: "percentage" },
        SGLD: { value: "72", type: "percentage" },
        BISS: { value: "69", type: "percentage" },
        TOTAL: { value: "67", type: "percentage" },
        AVERAGE: { value: "67", type: "percentage" },
      },
    },
    {
      name: "Retail (%)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "22", type: "percentage" },
        GTWH: { value: "20", type: "percentage" },
        SMWW: { value: "22", type: "percentage" },
        COMM: { value: "18", type: "percentage" },
        SM35: { value: "33", type: "percentage" },
        AUST: { value: "50", type: "percentage" },
        ROCK: { value: "42", type: "percentage" },
        TMBL: { value: "24", type: "percentage" },
        PSDA: { value: "26", type: "percentage" },
        HWY6: { value: "23", type: "percentage" },
        STFD: { value: "26", type: "percentage" },
        SGLD: { value: "28", type: "percentage" },
        BISS: { value: "21", type: "percentage" },
        TOTAL: { value: "27", type: "percentage" },
        AVERAGE: { value: "27", type: "percentage" },
      },
    },
    {
      name: "Fuel Sales ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "191188", type: "currency" },
        GTWH: { value: "123059", type: "currency" },
        SMWW: { value: "-119607", type: "currency" },
        COMM: { value: "90846", type: "currency" },
        SM35: { value: "50423", type: "currency" },
        AUST: { value: "27260", type: "currency" },
        ROCK: { value: "15372", type: "currency" },
        TMBL: { value: "78016", type: "currency" },
        PSDA: { value: "51275", type: "currency" },
        HWY6: { value: "62225", type: "currency" },
        STFD: { value: "56344", type: "currency" },
        SGLD: { value: "66901", type: "currency" },
        BISS: { value: "46126", type: "currency" },
        TOTAL: { value: "889884", type: "currency" },
        AVERAGE: { value: "88988", type: "currency" },
      },
    },
    {
      name: "Recurring + Prepaid ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "191188", type: "currency" },
        GTWH: { value: "123059", type: "currency" },
        SMWW: { value: "-119607", type: "currency" },
        COMM: { value: "90846", type: "currency" },
        SM35: { value: "50423", type: "currency" },
        AUST: { value: "27260", type: "currency" },
        ROCK: { value: "15372", type: "currency" },
        TMBL: { value: "78016", type: "currency" },
        PSDA: { value: "51275", type: "currency" },
        HWY6: { value: "62225", type: "currency" },
        STFD: { value: "56344", type: "currency" },
        SGLD: { value: "66901", type: "currency" },
        BISS: { value: "46126", type: "currency" },
        TOTAL: { value: "889884", type: "currency" },
        AVERAGE: { value: "88988", type: "currency" },
      },
    },
    {
      name: "Recurring ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "179517", type: "currency" },
        GTWH: { value: "116992", type: "currency" },
        SMWW: { value: "+115224", type: "currency" },
        COMM: { value: "85536", type: "currency" },
        SM35: { value: "46348", type: "currency" },
        AUST: { value: "14531", type: "currency" },
        ROCK: { value: "13406", type: "currency" },
        TMBL: { value: "76243", type: "currency" },
        PSDA: { value: "47672", type: "currency" },
        HWY6: { value: "59836", type: "currency" },
        STFD: { value: "54294", type: "currency" },
        SGLD: { value: "66851", type: "currency" },
        BISS: { value: "40551", type: "currency" },
        TOTAL: { value: "848653", type: "currency" },
        AVERAGE: { value: "84866", type: "currency" },
      },
    },
    {
      name: "Prepaid ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "11671", type: "currency" },
        GTWH: { value: "6066", type: "currency" },
        SMWW: { value: "+4383", type: "currency" },
        COMM: { value: "5266", type: "currency" },
        SM35: { value: "3976", type: "currency" },
        AUST: { value: "12729", type: "currency" },
        ROCK: { value: "1966", type: "currency" },
        TMBL: { value: "1772", type: "currency" },
        PSDA: { value: "3603", type: "currency" },
        HWY6: { value: "2389", type: "currency" },
        STFD: { value: "2050", type: "currency" },
        SGLD: { value: "50", type: "currency" },
        BISS: { value: "5575", type: "currency" },
        TOTAL: { value: "41226", type: "currency" },
        AVERAGE: { value: "4123", type: "currency" },
      },
    },
    {
      name: "Retail ($)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "55057", type: "currency" },
        GTWH: { value: "31128", type: "currency" },
        SMWW: { value: "+33654", type: "currency" },
        COMM: { value: "19882", type: "currency" },
        SM35: { value: "25108", type: "currency" },
        AUST: { value: "27397", type: "currency" },
        ROCK: { value: "11289", type: "currency" },
        TMBL: { value: "24223", type: "currency" },
        PSDA: { value: "17813", type: "currency" },
        HWY6: { value: "18089", type: "currency" },
        STFD: { value: "19596", type: "currency" },
        SGLD: { value: "26345", type: "currency" },
        BISS: { value: "12543", type: "currency" },
        TOTAL: { value: "270896", type: "currency" },
        AVERAGE: { value: "27090", type: "currency" },
      },
    },
    {
      name: "Recurring (%)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "73", type: "percentage" },
        GTWH: { value: "76", type: "percentage" },
        SMWW: { value: "+75", type: "percentage" },
        COMM: { value: "77", type: "percentage" },
        SM35: { value: "61", type: "percentage" },
        AUST: { value: "27", type: "percentage" },
        ROCK: { value: "50", type: "percentage" },
        TMBL: { value: "75", type: "percentage" },
        PSDA: { value: "69", type: "percentage" },
        HWY6: { value: "75", type: "percentage" },
        STFD: { value: "71", type: "percentage" },
        SGLD: { value: "72", type: "percentage" },
        BISS: { value: "69", type: "percentage" },
        TOTAL: { value: "67", type: "percentage" },
        AVERAGE: { value: "67", type: "percentage" },
      },
    },
    {
      name: "Retail (%)",
      category: "SALES (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "22", type: "percentage" },
        GTWH: { value: "20", type: "percentage" },
        SMWW: { value: "+22", type: "percentage" },
        COMM: { value: "18", type: "percentage" },
        SM35: { value: "33", type: "percentage" },
        AUST: { value: "50", type: "percentage" },
        ROCK: { value: "42", type: "percentage" },
        TMBL: { value: "24", type: "percentage" },
        PSDA: { value: "26", type: "percentage" },
        HWY6: { value: "23", type: "percentage" },
        STFD: { value: "26", type: "percentage" },
        SGLD: { value: "28", type: "percentage" },
        BISS: { value: "21", type: "percentage" },
        TOTAL: { value: "27", type: "percentage" },
        AVERAGE: { value: "27", type: "percentage" },
      },
    },

    // ==================== CAR COUNT (PACING) ====================
    {
      name: "CAR COUNT (PACING)",
      category: "CAR COUNT (PACING)",
      data: null,
    },
    {
      name: "Total car count (#)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "21899", type: "number" },
        GTWH: { value: "13281", type: "number" },
        SMWW: { value: "-10660", type: "number" },
        COMM: { value: "13491", type: "number" },
        SM35: { value: "9816", type: "number" },
        AUST: { value: "11776", type: "number" },
        ROCK: { value: "4216", type: "number" },
        TMBL: { value: "7755", type: "number" },
        PSDA: { value: "8792", type: "number" },
        HWY6: { value: "7840", type: "number" },
        STFD: { value: "8005", type: "number" },
        SGLD: { value: "8495", type: "number" },
        BISS: { value: "7871", type: "number" },
        TOTAL: { value: "110034", type: "number" },
        AVERAGE: { value: "11003", type: "number" },
      },
    },
    {
      name: "Recurring car count (#)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "17386", type: "number" },
        GTWH: { value: "10435", type: "number" },
        SMWW: { value: "+7890", type: "number" },
        COMM: { value: "11050", type: "number" },
        SM35: { value: "7331", type: "number" },
        AUST: { value: "7969", type: "number" },
        ROCK: { value: "2951", type: "number" },
        TMBL: { value: "5981", type: "number" },
        PSDA: { value: "6485", type: "number" },
        HWY6: { value: "6114", type: "number" },
        STFD: { value: "6090", type: "number" },
        SGLD: { value: "5989", type: "number" },
        BISS: { value: "6035", type: "number" },
        TOTAL: { value: "84751", type: "number" },
        AVERAGE: { value: "8475", type: "number" },
      },
    },
    {
      name: "Retail car count (#)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "4248", type: "number" },
        GTWH: { value: "2516", type: "number" },
        SMWW: { value: "+2548", type: "number" },
        COMM: { value: "1836", type: "number" },
        SM35: { value: "1899", type: "number" },
        AUST: { value: "3035", type: "number" },
        ROCK: { value: "840", type: "number" },
        TMBL: { value: "1698", type: "number" },
        PSDA: { value: "2082", type: "number" },
        HWY6: { value: "1488", type: "number" },
        STFD: { value: "1677", type: "number" },
        SGLD: { value: "2015", type: "number" },
        BISS: { value: "1224", type: "number" },
        TOTAL: { value: "22007", type: "number" },
        AVERAGE: { value: "2201", type: "number" },
      },
    },
    {
      name: "Free washes (#)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "265", type: "number" },
        GTWH: { value: "330", type: "number" },
        SMWW: { value: "+222", type: "number" },
        COMM: { value: "605", type: "number" },
        SM35: { value: "586", type: "number" },
        AUST: { value: "772", type: "number" },
        ROCK: { value: "425", type: "number" },
        TMBL: { value: "76", type: "number" },
        PSDA: { value: "225", type: "number" },
        HWY6: { value: "238", type: "number" },
        STFD: { value: "238", type: "number" },
        SGLD: { value: "491", type: "number" },
        BISS: { value: "612", type: "number" },
        TOTAL: { value: "3276", type: "number" },
        AVERAGE: { value: "328", type: "number" },
      },
    },
    {
      name: "Recurring car count (%)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "79", type: "percentage" },
        GTWH: { value: "79", type: "percentage" },
        SMWW: { value: "+74", type: "percentage" },
        COMM: { value: "82", type: "percentage" },
        SM35: { value: "75", type: "percentage" },
        AUST: { value: "68", type: "percentage" },
        ROCK: { value: "70", type: "percentage" },
        TMBL: { value: "77", type: "percentage" },
        PSDA: { value: "74", type: "percentage" },
        HWY6: { value: "78", type: "percentage" },
        STFD: { value: "76", type: "percentage" },
        SGLD: { value: "71", type: "percentage" },
        BISS: { value: "77", type: "percentage" },
        TOTAL: { value: "76", type: "percentage" },
        AVERAGE: { value: "76", type: "percentage" },
      },
    },
    {
      name: "Retail car count (%)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "19", type: "percentage" },
        GTWH: { value: "19", type: "percentage" },
        SMWW: { value: "+24", type: "percentage" },
        COMM: { value: "14", type: "percentage" },
        SM35: { value: "19", type: "percentage" },
        AUST: { value: "26", type: "percentage" },
        ROCK: { value: "20", type: "percentage" },
        TMBL: { value: "22", type: "percentage" },
        PSDA: { value: "24", type: "percentage" },
        HWY6: { value: "19", type: "percentage" },
        STFD: { value: "21", type: "percentage" },
        SGLD: { value: "24", type: "percentage" },
        BISS: { value: "16", type: "percentage" },
        TOTAL: { value: "20", type: "percentage" },
        AVERAGE: { value: "20", type: "percentage" },
      },
    },
    {
      name: "New customers (#)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "1479", type: "number" },
        GTWH: { value: "795", type: "number" },
        SMWW: { value: "+864", type: "number" },
        COMM: { value: "711", type: "number" },
        SM35: { value: "1155", type: "number" },
        AUST: { value: "2816", type: "number" },
        ROCK: { value: "744", type: "number" },
        TMBL: { value: "0", type: "number" },
        PSDA: { value: "564", type: "number" },
        HWY6: { value: "574", type: "number" },
        STFD: { value: "563", type: "number" },
        SGLD: { value: "901", type: "number" },
        BISS: { value: "0", type: "number" },
        TOTAL: { value: "6705", type: "number" },
        AVERAGE: { value: "745", type: "number" },
      },
    },
    {
      name: "New customers (%)",
      category: "CAR COUNT (PACING)",
      isSubMetric: true,
      data: {
        KYLE: { value: "6.77", type: "percentage" },
        GTWH: { value: "6.01", type: "percentage" },
        SMWW: { value: "+8.14", type: "percentage" },
        COMM: { value: "5.31", type: "percentage" },
        SM35: { value: "11.82", type: "percentage" },
        AUST: { value: "24.0", type: "percentage" },
        ROCK: { value: "17.74", type: "percentage" },
        TMBL: { value: "0", type: "percentage" },
        PSDA: { value: "6.43", type: "percentage" },
        HWY6: { value: "7.37", type: "percentage" },
        STFD: { value: "7.08", type: "percentage" },
        SGLD: { value: "11.58", type: "percentage" },
        BISS: { value: "0", type: "percentage" },
        TOTAL: { value: "6.55", type: "percentage" },
        AVERAGE: { value: "6.55", type: "percentage" },
      },
    },

    // ==================== MEMBERSHIPS ====================
    {
      name: "MEMBERSHIPS",
      category: "MEMBERSHIPS",
      data: null,
    },
    {
      name: "Member count",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+6668", type: "number" },
        GTWH: { value: "+4449", type: "number" },
        SMWW: { value: "+4105", type: "number" },
        COMM: { value: "+3486", type: "number" },
        SM35: { value: "1916", type: "number" },
        AUST: { value: "2503", type: "number" },
        ROCK: { value: "546", type: "number" },
        TMBL: { value: "-2654", type: "number" },
        PSDA: { value: "-2211", type: "number" },
        HWY6: { value: "2506", type: "number" },
        STFD: { value: "2415", type: "number" },
        SGLD: { value: "2660", type: "number" },
        BISS: { value: "1785", type: "number" },
        TOTAL: { value: "33070", type: "number" },
        AVERAGE: { value: "3307", type: "number" },
      },
    },
    {
      name: "Avg. renewal rate",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+26.92", type: "currency" },
        GTWH: { value: "+26.3", type: "currency" },
        SMWW: { value: "28.07", type: "currency" },
        COMM: { value: "24.55", type: "currency" },
        SM35: { value: "24.24", type: "currency" },
        AUST: { value: "-5.81", type: "currency" },
        ROCK: { value: "24.55", type: "currency" },
        TMBL: { value: "28.73", type: "currency" },
        PSDA: { value: "21.56", type: "currency" },
        HWY6: { value: "23.88", type: "currency" },
        STFD: { value: "22.48", type: "currency" },
        SGLD: { value: "25.13", type: "currency" },
        BISS: { value: "22.72", type: "currency" },
        TOTAL: { value: "25.19", type: "currency" },
        AVERAGE: { value: "25.19", type: "currency" },
      },
    },
    {
      name: "Conversion rate (%)",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+17.35", type: "percentage" },
        GTWH: { value: "15.74", type: "percentage" },
        SMWW: { value: "11.38", type: "percentage" },
        COMM: { value: "+20.37", type: "percentage" },
        SM35: { value: "16.85", type: "percentage" },
        AUST: { value: "+42.73", type: "percentage" },
        ROCK: { value: "14.17", type: "percentage" },
        TMBL: { value: "-9.19", type: "percentage" },
        PSDA: { value: "13.4", type: "percentage" },
        HWY6: { value: "15.19", type: "percentage" },
        STFD: { value: "14.85", type: "percentage" },
        SGLD: { value: "-9.58", type: "percentage" },
        BISS: { value: "+33.01", type: "percentage" },
        TOTAL: { value: "14.39", type: "percentage" },
        AVERAGE: { value: "14.39", type: "percentage" },
      },
    },
    {
      name: "Churn rate (%)",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "-9.6", type: "percentage" },
        GTWH: { value: "-8.43", type: "percentage" },
        SMWW: { value: "-7.5", type: "percentage" },
        COMM: { value: "-9.81", type: "percentage" },
        SM35: { value: "-9.5", type: "percentage" },
        AUST: { value: "-12.18", type: "percentage" },
        ROCK: { value: "-14.1", type: "percentage" },
        TMBL: { value: "-7.46", type: "percentage" },
        PSDA: { value: "-10.76", type: "percentage" },
        HWY6: { value: "-9.82", type: "percentage" },
        STFD: { value: "-9.03", type: "percentage" },
        SGLD: { value: "-10.34", type: "percentage" },
        BISS: { value: "-14.68", type: "percentage" },
        TOTAL: { value: "-9.22", type: "percentage" },
        AVERAGE: { value: "-9.22", type: "percentage" },
      },
    },
    {
      name: "Members added",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+737", type: "number" },
        GTWH: { value: "+396", type: "number" },
        SMWW: { value: "+290", type: "number" },
        COMM: { value: "+374", type: "number" },
        SM35: { value: "+320", type: "number" },
        AUST: { value: "+1297", type: "number" },
        ROCK: { value: "+119", type: "number" },
        TMBL: { value: "+156", type: "number" },
        PSDA: { value: "+279", type: "number" },
        HWY6: { value: "+226", type: "number" },
        STFD: { value: "+249", type: "number" },
        SGLD: { value: "+193", type: "number" },
        BISS: { value: "+404", type: "number" },
        TOTAL: { value: "+3220", type: "number" },
        AVERAGE: { value: "+322", type: "number" },
      },
    },
    {
      name: "Members deactivated",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "-640", type: "number" },
        GTWH: { value: "-375", type: "number" },
        SMWW: { value: "-308", type: "number" },
        COMM: { value: "-342", type: "number" },
        SM35: { value: "-182", type: "number" },
        AUST: { value: "-1206", type: "number" },
        ROCK: { value: "-77", type: "number" },
        TMBL: { value: "-198", type: "number" },
        PSDA: { value: "-238", type: "number" },
        HWY6: { value: "-246", type: "number" },
        STFD: { value: "-218", type: "number" },
        SGLD: { value: "-275", type: "number" },
        BISS: { value: "-262", type: "number" },
        TOTAL: { value: "-3022", type: "number" },
        AVERAGE: { value: "-302", type: "number" },
      },
    },
    {
      name: "Net members added",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+97", type: "number" },
        GTWH: { value: "+21", type: "number" },
        SMWW: { value: "-18", type: "number" },
        COMM: { value: "+32", type: "number" },
        SM35: { value: "+138", type: "number" },
        AUST: { value: "+2503", type: "number" },
        ROCK: { value: "+42", type: "number" },
        TMBL: { value: "-42", type: "number" },
        PSDA: { value: "+41", type: "number" },
        HWY6: { value: "-20", type: "number" },
        STFD: { value: "+31", type: "number" },
        SGLD: { value: "-82", type: "number" },
        BISS: { value: "+142", type: "number" },
        TOTAL: { value: "+198", type: "number" },
        AVERAGE: { value: "+20", type: "number" },
      },
    },
    {
      name: "Net members added (%)",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "+1.45", type: "percentage" },
        GTWH: { value: "+0.47", type: "percentage" },
        SMWW: { value: "-0.44", type: "percentage" },
        COMM: { value: "+0.92", type: "percentage" },
        SM35: { value: "+7.2", type: "percentage" },
        AUST: { value: "+100", type: "percentage" },
        ROCK: { value: "+7.69", type: "percentage" },
        TMBL: { value: "-1.58", type: "percentage" },
        PSDA: { value: "+1.85", type: "percentage" },
        HWY6: { value: "-0.8", type: "percentage" },
        STFD: { value: "+1.28", type: "percentage" },
        SGLD: { value: "-3.08", type: "percentage" },
        BISS: { value: "+7.96", type: "percentage" },
        TOTAL: { value: "+0.73", type: "percentage" },
        AVERAGE: { value: "2.65", type: "percentage" },
      },
    },
    {
      name: "Average usage per month",
      category: "MEMBERSHIPS",
      isSubMetric: true,
      data: {
        KYLE: { value: "2.61", type: "number" },
        GTWH: { value: "2.35", type: "number" },
        SMWW: { value: "1.92", type: "number" },
        COMM: { value: "3.17", type: "number" },
        SM35: { value: "3.83", type: "number" },
        AUST: { value: "3.18", type: "number" },
        ROCK: { value: "5.4", type: "number" },
        TMBL: { value: "2.25", type: "number" },
        PSDA: { value: "2.93", type: "number" },
        HWY6: { value: "2.44", type: "number" },
        STFD: { value: "2.52", type: "number" },
        SGLD: { value: "2.44", type: "number" },
        BISS: { value: "3.38", type: "number" },
        TOTAL: { value: "2.65", type: "number" },
        AVERAGE: { value: "2.65", type: "number" },
      },
    },

    // ==================== $/CAR ====================
    {
      name: "$/CAR",
      category: "$/CAR",
      data: null,
    },
    {
      name: "$/car - remove free washes",
      category: "$/CAR",
      isSubMetric: true,
      data: {
        KYLE: { value: "+11.38", type: "currency" },
        GTWH: { value: "+11.91", type: "currency" },
        SMWW: { value: "+14.68", type: "currency" },
        COMM: { value: "8.59", type: "currency" },
        SM35: { value: "8.18", type: "currency" },
        AUST: { value: "-4.97", type: "currency" },
        ROCK: { value: "7.03", type: "currency" },
        TMBL: { value: "+13.31", type: "currency" },
        PSDA: { value: "8.06", type: "currency" },
        HWY6: { value: "10.56", type: "currency" },
        STFD: { value: "9.78", type: "currency" },
        SGLD: { value: "+11.65", type: "currency" },
        BISS: { value: "8.08", type: "currency" },
        TOTAL: { value: "10.81", type: "currency" },
        AVERAGE: { value: "10.81", type: "currency" },
      },
    },
    {
      name: "Retail $/car",
      category: "$/CAR",
      isSubMetric: true,
      data: {
        KYLE: { value: "13.82", type: "currency" },
        GTWH: { value: "14.24", type: "currency" },
        SMWW: { value: "14.47", type: "currency" },
        COMM: { value: "16.15", type: "currency" },
        SM35: { value: "19.12", type: "currency" },
        AUST: { value: "12.11", type: "currency" },
        ROCK: { value: "27.2", type: "currency" },
        TMBL: { value: "14.93", type: "currency" },
        PSDA: { value: "9.59", type: "currency" },
        HWY6: { value: "14.47", type: "currency" },
        STFD: { value: "13.62", type: "currency" },
        SGLD: { value: "17.29", type: "currency" },
        BISS: { value: "20.49", type: "currency" },
        TOTAL: { value: "14.17", type: "currency" },
        AVERAGE: { value: "14.17", type: "currency" },
      },
    },
    {
      name: "Member $/car",
      category: "$/CAR",
      isSubMetric: true,
      data: {
        KYLE: { value: "10.33", type: "currency" },
        GTWH: { value: "11.21", type: "currency" },
        SMWW: { value: "14.6", type: "currency" },
        COMM: { value: "7.74", type: "currency" },
        SM35: { value: "6.34", type: "currency" },
        AUST: { value: "1.82", type: "currency" },
        ROCK: { value: "4.54", type: "currency" },
        TMBL: { value: "12.75", type: "currency" },
        PSDA: { value: "7.35", type: "currency" },
        HWY6: { value: "9.79", type: "currency" },
        STFD: { value: "8.92", type: "currency" },
        SGLD: { value: "11.16", type: "currency" },
        BISS: { value: "6.72", type: "currency" },
        TOTAL: { value: "9.02", type: "currency" },
        AVERAGE: { value: "9.02", type: "currency" },
      },
    },

    // ==================== PACKAGE MIX ====================
    {
      name: "PACKAGE MIX",
      category: "PACKAGE MIX",
      data: null,
    },
    {
      name: "RETAIL SALES",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: null,
    },
    {
      name: "Sudsy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "18.63", type: "percentage" },
        GTWH: { value: "23.55", type: "percentage" },
        SMWW: { value: "18.15", type: "percentage" },
        COMM: { value: "16.0", type: "percentage" },
        SM35: { value: "12.71", type: "percentage" },
        AUST: { value: "11.46", type: "percentage" },
        ROCK: { value: "22.58", type: "percentage" },
        TMBL: { value: "12.26", type: "percentage" },
        PSDA: { value: "38.57", type: "percentage" },
        HWY6: { value: "6.07", type: "percentage" },
        STFD: { value: "15.03", type: "percentage" },
        SGLD: { value: "0", type: "percentage" },
        BISS: { value: "4.8", type: "percentage" },
        TOTAL: { value: "17.89", type: "percentage" },
        AVERAGE: { value: "17.89", type: "percentage" },
      },
    },
    {
      name: "Deluxe (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "17.06", type: "percentage" },
        GTWH: { value: "14.91", type: "percentage" },
        SMWW: { value: "17.4", type: "percentage" },
        COMM: { value: "11.01", type: "percentage" },
        SM35: { value: "16.61", type: "percentage" },
        AUST: { value: "15.58", type: "percentage" },
        ROCK: { value: "21.01", type: "percentage" },
        TMBL: { value: "16.39", type: "percentage" },
        PSDA: { value: "8.57", type: "percentage" },
        HWY6: { value: "7.97", type: "percentage" },
        STFD: { value: "13.25", type: "percentage" },
        SGLD: { value: "0", type: "percentage" },
        BISS: { value: "12.3", type: "percentage" },
        TOTAL: { value: "13.69", type: "percentage" },
        AVERAGE: { value: "13.69", type: "percentage" },
      },
    },
    {
      name: "Spiffy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "33.65", type: "percentage" },
        GTWH: { value: "31.21", type: "percentage" },
        SMWW: { value: "32.97", type: "percentage" },
        COMM: { value: "22.96", type: "percentage" },
        SM35: { value: "32.86", type: "percentage" },
        AUST: { value: "31.38", type: "percentage" },
        ROCK: { value: "33.57", type: "percentage" },
        TMBL: { value: "30.14", type: "percentage" },
        PSDA: { value: "20.84", type: "percentage" },
        HWY6: { value: "24.29", type: "percentage" },
        STFD: { value: "22.75", type: "percentage" },
        SGLD: { value: "0", type: "percentage" },
        BISS: { value: "31.38", type: "percentage" },
        TOTAL: { value: "27.96", type: "percentage" },
        AVERAGE: { value: "27.96", type: "percentage" },
      },
    },
    {
      name: "Thrifty (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "30.66", type: "percentage" },
        GTWH: { value: "30.33", type: "percentage" },
        SMWW: { value: "31.48", type: "percentage" },
        COMM: { value: "50.03", type: "percentage" },
        SM35: { value: "37.82", type: "percentage" },
        AUST: { value: "41.59", type: "percentage" },
        ROCK: { value: "22.83", type: "percentage" },
        TMBL: { value: "41.21", type: "percentage" },
        PSDA: { value: "32.02", type: "percentage" },
        HWY6: { value: "61.67", type: "percentage" },
        STFD: { value: "48.98", type: "percentage" },
        SGLD: { value: "0", type: "percentage" },
        BISS: { value: "51.52", type: "percentage" },
        TOTAL: { value: "40.47", type: "percentage" },
        AVERAGE: { value: "40.47", type: "percentage" },
      },
    },
    {
      name: "MEMBERSHIP SALES",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: null,
    },
    {
      name: "Sudsy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "19.97", type: "percentage" },
        GTWH: { value: "18.72", type: "percentage" },
        SMWW: { value: "26.65", type: "percentage" },
        COMM: { value: "16.01", type: "percentage" },
        SM35: { value: "46.05", type: "percentage" },
        AUST: { value: "50.92", type: "percentage" },
        ROCK: { value: "20.8", type: "percentage" },
        TMBL: { value: "15.48", type: "percentage" },
        PSDA: { value: "26.76", type: "percentage" },
        HWY6: { value: "20.85", type: "percentage" },
        STFD: { value: "28.78", type: "percentage" },
        SGLD: { value: "22.8", type: "percentage" },
        BISS: { value: "16.98", type: "percentage" },
        TOTAL: { value: "24.21", type: "percentage" },
        AVERAGE: { value: "24.21", type: "percentage" },
      },
    },
    {
      name: "Deluxe (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "17.4", type: "percentage" },
        GTWH: { value: "15.64", type: "percentage" },
        SMWW: { value: "14.42", type: "percentage" },
        COMM: { value: "14.29", type: "percentage" },
        SM35: { value: "9.28", type: "percentage" },
        AUST: { value: "13.98", type: "percentage" },
        ROCK: { value: "21.6", type: "percentage" },
        TMBL: { value: "7.74", type: "percentage" },
        PSDA: { value: "10.92", type: "percentage" },
        HWY6: { value: "9.27", type: "percentage" },
        STFD: { value: "9.59", type: "percentage" },
        SGLD: { value: "20.21", type: "percentage" },
        BISS: { value: "10.14", type: "percentage" },
        TOTAL: { value: "12.88", type: "percentage" },
        AVERAGE: { value: "12.88", type: "percentage" },
      },
    },
    {
      name: "Spiffy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "27.96", type: "percentage" },
        GTWH: { value: "26.3", type: "percentage" },
        SMWW: { value: "28.53", type: "percentage" },
        COMM: { value: "21.43", type: "percentage" },
        SM35: { value: "15.46", type: "percentage" },
        AUST: { value: "14.55", type: "percentage" },
        ROCK: { value: "19.2", type: "percentage" },
        TMBL: { value: "25.0", type: "percentage" },
        PSDA: { value: "19.37", type: "percentage" },
        HWY6: { value: "16.99", type: "percentage" },
        STFD: { value: "18.45", type: "percentage" },
        SGLD: { value: "22.28", type: "percentage" },
        BISS: { value: "20.28", type: "percentage" },
        TOTAL: { value: "22.18", type: "percentage" },
        AVERAGE: { value: "22.18", type: "percentage" },
      },
    },
    {
      name: "Thrifty (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "22.29", type: "percentage" },
        GTWH: { value: "27.73", type: "percentage" },
        SMWW: { value: "13.48", type: "percentage" },
        COMM: { value: "38.67", type: "percentage" },
        SM35: { value: "12.03", type: "percentage" },
        AUST: { value: "17.43", type: "percentage" },
        ROCK: { value: "15.2", type: "percentage" },
        TMBL: { value: "12.5", type: "percentage" },
        PSDA: { value: "29.23", type: "percentage" },
        HWY6: { value: "46.33", type: "percentage" },
        STFD: { value: "24.72", type: "percentage" },
        SGLD: { value: "34.72", type: "percentage" },
        BISS: { value: "40.8", type: "percentage" },
        TOTAL: { value: "26.17", type: "percentage" },
        AVERAGE: { value: "26.17", type: "percentage" },
      },
    },
    {
      name: "CURRENT MEMBERSHIP MIX",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: null,
    },
    {
      name: "Sudsy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "29.54", type: "percentage" },
        GTWH: { value: "27.8", type: "percentage" },
        SMWW: { value: "29.04", type: "percentage" },
        COMM: { value: "18.53", type: "percentage" },
        SM35: { value: "25.78", type: "percentage" },
        AUST: { value: "55.29", type: "percentage" },
        ROCK: { value: "34.62", type: "percentage" },
        TMBL: { value: "26.9", type: "percentage" },
        PSDA: { value: "29.76", type: "percentage" },
        HWY6: { value: "15.96", type: "percentage" },
        STFD: { value: "19.3", type: "percentage" },
        SGLD: { value: "27.19", type: "percentage" },
        BISS: { value: "20.73", type: "percentage" },
        TOTAL: { value: "24.98", type: "percentage" },
        AVERAGE: { value: "24.98", type: "percentage" },
      },
    },
    {
      name: "Deluxe (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "19.44", type: "percentage" },
        GTWH: { value: "15.73", type: "percentage" },
        SMWW: { value: "24.87", type: "percentage" },
        COMM: { value: "15.66", type: "percentage" },
        SM35: { value: "15.55", type: "percentage" },
        AUST: { value: "15.18", type: "percentage" },
        ROCK: { value: "16.67", type: "percentage" },
        TMBL: { value: "21.7", type: "percentage" },
        PSDA: { value: "15.33", type: "percentage" },
        HWY6: { value: "9.98", type: "percentage" },
        STFD: { value: "18.01", type: "percentage" },
        SGLD: { value: "17.76", type: "percentage" },
        BISS: { value: "10.81", type: "percentage" },
        TOTAL: { value: "17.4", type: "percentage" },
        AVERAGE: { value: "17.4", type: "percentage" },
      },
    },
    {
      name: "Spiffy (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "23.23", type: "percentage" },
        GTWH: { value: "21.87", type: "percentage" },
        SMWW: { value: "21.02", type: "percentage" },
        COMM: { value: "16.98", type: "percentage" },
        SM35: { value: "23.54", type: "percentage" },
        AUST: { value: "18.22", type: "percentage" },
        ROCK: { value: "20.88", type: "percentage" },
        TMBL: { value: "22.68", type: "percentage" },
        PSDA: { value: "19.36", type: "percentage" },
        HWY6: { value: "16.6", type: "percentage" },
        STFD: { value: "15.82", type: "percentage" },
        SGLD: { value: "19.61", type: "percentage" },
        BISS: { value: "21.51", type: "percentage" },
        TOTAL: { value: "20.07", type: "percentage" },
        AVERAGE: { value: "20.07", type: "percentage" },
      },
    },
    {
      name: "Thrifty (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "20.08", type: "percentage" },
        GTWH: { value: "20.86", type: "percentage" },
        SMWW: { value: "18.59", type: "percentage" },
        COMM: { value: "43.0", type: "percentage" },
        SM35: { value: "23.9", type: "percentage" },
        AUST: { value: "22.29", type: "percentage" },
        ROCK: { value: "19.78", type: "percentage" },
        TMBL: { value: "21.48", type: "percentage" },
        PSDA: { value: "31.84", type: "percentage" },
        HWY6: { value: "53.83", type: "percentage" },
        STFD: { value: "44.55", type: "percentage" },
        SGLD: { value: "32.69", type: "percentage" },
        BISS: { value: "47.56", type: "percentage" },
        TOTAL: { value: "31.08", type: "percentage" },
        AVERAGE: { value: "31.08", type: "percentage" },
      },
    },
    {
      name: "Community Sudsy Special (%)",
      category: "PACKAGE MIX",
      isSubMetric: true,
      data: {
        KYLE: { value: "9.25", type: "percentage" },
        GTWH: { value: "14.61", type: "percentage" },
        SMWW: { value: "8.53", type: "percentage" },
        COMM: { value: "9.35", type: "percentage" },
        SM35: { value: "13.05", type: "percentage" },
        AUST: { value: "0.28", type: "percentage" },
        ROCK: { value: "12.45", type: "percentage" },
        TMBL: { value: "7.46", type: "percentage" },
        PSDA: { value: "4.03", type: "percentage" },
        HWY6: { value: "4.67", type: "percentage" },
        STFD: { value: "3.4", type: "percentage" },
        SGLD: { value: "4.01", type: "percentage" },
        BISS: { value: "1.62", type: "percentage" },
        TOTAL: { value: "7.84", type: "percentage" },
        AVERAGE: { value: "7.84", type: "percentage" },
      },
    },

    // ==================== LABOR ====================
    {
      name: "LABOR",
      category: "LABOR",
      data: null,
    },
    {
      name: "Total hours",
      category: "LABOR",
      isSubMetric: true,
      data: {
        KYLE: { value: "1280.26", type: "number" },
        GTWH: { value: "1026.28", type: "number" },
        SMWW: { value: "1050.54", type: "number" },
        COMM: { value: "1056.84", type: "number" },
        SM35: { value: "1003.42", type: "number" },
        AUST: { value: "1243.41", type: "number" },
        ROCK: { value: "824.97", type: "number" },
        TMBL: { value: "1083.71", type: "number" },
        PSDA: { value: "999.86", type: "number" },
        HWY6: { value: "1079.43", type: "number" },
        STFD: { value: "1012.57", type: "number" },
        SGLD: { value: "1048.7", type: "number" },
        BISS: { value: "1033.75", type: "number" },
        TOTAL: { value: "13643.74", type: "number" },
        AVERAGE: { value: "1049.52", type: "number" },
      },
    },
    {
      name: "Cars/labor hour",
      category: "LABOR",
      isSubMetric: true,
      data: {
        KYLE: { value: "+17.1", type: "number" },
        GTWH: { value: "+12.9", type: "number" },
        SMWW: { value: "+10.1", type: "number" },
        COMM: { value: "+12.8", type: "number" },
        SM35: { value: "9.8", type: "number" },
        AUST: { value: "9.5", type: "number" },
        ROCK: { value: "-5.1", type: "number" },
        TMBL: { value: "7.2", type: "number" },
        PSDA: { value: "8.8", type: "number" },
        HWY6: { value: "7.3", type: "number" },
        STFD: { value: "7.9", type: "number" },
        SGLD: { value: "8.1", type: "number" },
        BISS: { value: "7.6", type: "number" },
        TOTAL: { value: "10.2", type: "number" },
        AVERAGE: { value: "10.2", type: "number" },
      },
    },
    {
      name: "Regular hours",
      category: "LABOR",
      isSubMetric: true,
      data: {
        KYLE: { value: "1211.59", type: "number" },
        GTWH: { value: "904.22", type: "number" },
        SMWW: { value: "990.79", type: "number" },
        COMM: { value: "958.42", type: "number" },
        SM35: { value: "949.69", type: "number" },
        AUST: { value: "1189.25", type: "number" },
        ROCK: { value: "743.76", type: "number" },
        TMBL: { value: "969.49", type: "number" },
        PSDA: { value: "954.52", type: "number" },
        HWY6: { value: "910.99", type: "number" },
        STFD: { value: "736.86", type: "number" },
        SGLD: { value: "1048.7", type: "number" },
        BISS: { value: "862.9", type: "number" },
        TOTAL: { value: "12431.18", type: "number" },
        AVERAGE: { value: "956.24", type: "number" },
      },
    },
    {
      name: "OT hours",
      category: "LABOR",
      isSubMetric: true,
      data: {
        KYLE: { value: "-68.67", type: "number" },
        GTWH: { value: "-122.06", type: "number" },
        SMWW: { value: "-59.75", type: "number" },
        COMM: { value: "-98.42", type: "number" },
        SM35: { value: "-53.73", type: "number" },
        AUST: { value: "-54.16", type: "number" },
        ROCK: { value: "-81.21", type: "number" },
        TMBL: { value: "-114.22", type: "number" },
        PSDA: { value: "-45.34", type: "number" },
        HWY6: { value: "-168.44", type: "number" },
        STFD: { value: "-275.71", type: "number" },
        SGLD: { value: "0", type: "number" },
        BISS: { value: "-170.85", type: "number" },
        TOTAL: { value: "-1312.56", type: "number" },
        AVERAGE: { value: "-100.97", type: "number" },
      },
    },
    {
      name: "OT as a % of total hours",
      category: "LABOR",
      isSubMetric: true,
      data: {
        KYLE: { value: "-5.36", type: "percentage" },
        GTWH: { value: "-11.89", type: "percentage" },
        SMWW: { value: "-5.69", type: "percentage" },
        COMM: { value: "-9.31", type: "percentage" },
        SM35: { value: "-5.35", type: "percentage" },
        AUST: { value: "-4.36", type: "percentage" },
        ROCK: { value: "-9.84", type: "percentage" },
        TMBL: { value: "-10.54", type: "percentage" },
        PSDA: { value: "-4.53", type: "percentage" },
        HWY6: { value: "-15.6", type: "percentage" },
        STFD: { value: "-27.23", type: "percentage" },
        SGLD: { value: "0", type: "percentage" },
        BISS: { value: "-16.53", type: "percentage" },
        TOTAL: { value: "-9.55", type: "percentage" },
        AVERAGE: { value: "-9.87", type: "percentage" },
      },
    },
  ],
}